export const EventType = {
    NONE: 'none',
    DEFAULT: 'default',
    SNAP: 'snap',
    DRAG_PAGE: 'drag_page',
    PAGE_ZOOM: 'page_zoom',
    MOUSE_POINT: 'mouse_point',
    LINE: 'line',
    RECT: 'RECT',
    TRIANGLE: 'triangle',
    CIRCLE: 'circle',
    IMAGE: 'image',
    POLYGON: 'polygon',
    SELECT: 'select',
}