export const EventType = {
    NONE: 'none',
    DEFAULT: 'default',
    SNAP: 'snap',
    DRAG_PAGE: 'drag_page',
    PAGE_ZOOM: 'page_zoom',
    MOUSE_POINT: 'mouse_point',
    CREATE_LINE: 'create_line',
    CREATE_RECT: 'create_rect',
    CREATE_TRIANGLE: 'create)triangle',
    CREATE_CIRCLE: 'create_circle',
    CREATE_IMAGE: 'create_image',
    CREATE_LABEL: 'create_label',
    CREATE_POLYGON: 'create_polygon',
    SELECT: 'select',
}